version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dietintel_test_redis
    ports:
      - "6380:6379"  # Different port to avoid conflicts with local Redis
    command: redis-server --appendonly yes
    volumes:
      - test_redis_data:/data
    networks:
      - test_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: dietintel_test_app
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///./test_dietintel.db
      - ENVIRONMENT=test
    volumes:
      - .:/app
      - ./htmlcov:/app/htmlcov  # Mount coverage reports directory
      - ./test_dietintel.db:/app/test_dietintel.db  # Mount test database
    networks:
      - test_network
    working_dir: /app
    command: tail -f /dev/null  # Keep container running for interactive testing

volumes:
  test_redis_data:

networks:
  test_network:
    driver: bridge