import { StyleSheet, Platform } from 'react-native';

export const homeDashboardStyles = StyleSheet.create({
  homeContainer: {
    flex: 1,
  },
  homeSpacer: {
    height: 12,
  },
  actionsContainer: {
    paddingBottom: 16,
    paddingTop: 8,
    paddingHorizontal: 16,
    backgroundColor: '#0A1324',
    borderTopWidth: 1,
    borderTopColor: 'rgba(147, 197, 253, 0.2)',
  },
  header: {
    backgroundColor: '#070C1A',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 34 : 26,
    paddingBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  headerActionButton: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    width: 36,
    height: 36,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerActionButtonText: {
    color: 'white',
    fontSize: 16,
  },
  hero: {
    marginTop: 16,
    borderRadius: 24,
    backgroundColor: '#0b1f3a',
    padding: 20,
    overflow: 'hidden',
    position: 'relative',
  },
  heroGlow: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 100,
    backgroundColor: 'rgba(59, 130, 246, 0.35)',
    top: -40,
    right: -20,
  },
  heroContent: {
    marginBottom: 16,
  },
  heroTitle: {
    color: 'white',
    fontSize: 28,
    fontWeight: '700',
  },
  heroSubtitle: {
    color: '#E0E7FF',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 4,
  },
  heroVersion: {
    color: '#93C5FD',
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 4,
  },
  heroMetrics: {
    flexDirection: 'row',
    gap: 12,
  },
  heroStat: {
    flex: 1,
    minWidth: 0,
  },
  heroStatLabel: {
    color: '#A5B4FC',
    fontSize: 12,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  heroStatValue: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 6,
  },
  heroStatSubValue: {
    color: '#C7D2FE',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  navigationSection: {
    backgroundColor: 'white',
    paddingHorizontal: 16,
    paddingVertical: 40,
    marginTop: 20,
    flexDirection: 'column',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  headerContent: {
    gap: 4,
    flexShrink: 1,
  },
  headerTitle: {
    color: 'white',
    fontSize: 22,
    fontWeight: '700',
  },
  headerSubtitle: {
    color: '#C7D2FE',
    fontSize: 14,
    fontWeight: '500',
  },
  headerUtilitiesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 18,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  headerUtilityButton: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  headerUtilityText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  summaryCard: {
    marginTop: 10,
    borderRadius: 20,
    backgroundColor: '#0b1f3a',
    padding: 16,
  },
  summaryTitle: {
    color: '#C7D2FE',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  summaryCalories: {
    color: 'white',
    fontSize: 22,
    fontWeight: '700',
    marginTop: 6,
  },
  summaryStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  summaryStat: {
    flex: 1,
  },
  summaryStatLabel: {
    color: '#A5B4FC',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  summaryStatValue: {
    color: '#E0E7FF',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  summaryProgressTrack: {
    marginTop: 8,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.35)',
    overflow: 'hidden',
  },
  summaryProgressFill: {
    height: '100%',
    backgroundColor: '#60A5FA',
  },
  summaryHelperText: {
    color: '#E0E7FF',
    fontSize: 11,
    marginTop: 8,
  },
  summaryCtaText: {
    color: 'white',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 10,
  },
  quickActionsRow: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 8,
  },
  quickActionButton: {
    flex: 1,
    backgroundColor: '#1E3A8A',
    borderRadius: 16,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(191, 219, 254, 0.5)',
  },
  quickActionText: {
    color: '#EFF6FF',
    fontSize: 13,
    fontWeight: '600',
  },
  actionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingTop: 8,
  },
  actionTile: {
    width: '31%',
    backgroundColor: '#1E3A8A',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    minHeight: 62,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(191, 219, 254, 0.5)',
  },
  actionTileIcon: {
    color: '#EFF6FF',
    fontSize: 16,
    marginBottom: 4,
  },
  actionTileText: {
    color: '#EFF6FF',
    fontSize: 12,
    fontWeight: '600',
  },
  insightsRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  insightItem: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 12,
  },
  insightLabel: {
    color: '#64748B',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  insightValue: {
    color: '#0b1f3a',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 6,
  },
});
