- name: Generate AI review with Codex
  env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    LC_ALL: C.UTF-8
  run: |
    jq -n --rawfile diff diff.patch '
    {
      model: "gpt-5-codex-medium",
      input: [
        {
          "role": "system",
          "content": "Actúa como revisor senior. Devuelve: 1) issues por severidad (Alta/Media/Baja) con file:line y motivo; 2) parches propuestos en diff unificado; 3) riesgos de regresión y tests faltantes; 4) marca ⚠️ si viola el DevSpec/scope. Sé conciso."
        },
        {
          "role": "user",
          "content": (
            "Aquí está el diff unificado de la PR:\n```diff\n"
            + $diff
            + "\n```"
          )
        }
      ],
      temperature: 0,
      max_output_tokens: 16000
    }' > body.json

    curl -s https://api.openai.com/v1/responses \
      -H "Authorization: Bearer $OPENAI_API_KEY" \
      -H "Content-Type: application/json" \
      -d @body.json \
    | jq -r '.output_text // .choices[0].message.content // .content[0].text // "Sin respuesta del modelo."' > review.md
